# Project information
site_name: quick_preprocessing
# defeine TOC or order of website-
nav:
  - Home: index.md
  - APIrefrence: APIreference.md
site_author: Ankur Das
site_description: >-
  A library which can be used to quickly preprocess text data that includes removal of punctuations, stopwords, lowering and also
  can lemmatize each words or can do stemming just by importing the library.

# Repository
repo_name: AnkurDas-krypto/quick_preprocessing
repo_url: https://github.com/AnkurDas-krypto/quick_preprocessing

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/AnkurDas-krypto

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ankur-das-151571192/


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/AnkurDas-krypto"  target="_blank" rel="noopener">Ankur Das</a>